version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    restart: always
    ports:
      - 8000:8000

  redis:
    image: redis:alpine
    restart: always

  celery:
    build:
      context: .
      dockerfile: celery_worker.dockerfile
    restart: always
    depends_on:
      - redis

  flower:
    image: mher/flower:1.2
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: always
    ports:
      - 5555:5555
    depends_on:
      - celery
